CREATE TABLE user_ai_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    model_config_id VARCHAR(64) NOT NULL,
    channel_id VARCHAR(64) NOT NULL,
    model_name VARCHAR(200) NOT NULL,
    model_type VARCHAR(20) NOT NULL,
    capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_ai_model_configs_id UNIQUE (user_id, model_config_id),
    CONSTRAINT uk_user_ai_model_configs_model UNIQUE (user_id, channel_id, model_name, model_type),
    CONSTRAINT ck_user_ai_model_configs_type CHECK (model_type IN ('image', 'video', 'text'))
);

COMMENT ON TABLE user_ai_model_configs IS '用户可用AI模型配置表';
COMMENT ON COLUMN user_ai_model_configs.id IS '模型配置记录ID';
COMMENT ON COLUMN user_ai_model_configs.user_id IS '用户ID';
COMMENT ON COLUMN user_ai_model_configs.model_config_id IS '前端模型配置ID';
COMMENT ON COLUMN user_ai_model_configs.channel_id IS '所属渠道ID';
COMMENT ON COLUMN user_ai_model_configs.model_name IS '模型名称';
COMMENT ON COLUMN user_ai_model_configs.model_type IS '模型类型：image、video、text';
COMMENT ON COLUMN user_ai_model_configs.capabilities IS '模型能力列表JSON';
COMMENT ON COLUMN user_ai_model_configs.is_default IS '是否为该类型默认模型';
COMMENT ON COLUMN user_ai_model_configs.sort_order IS '排序值';
COMMENT ON COLUMN user_ai_model_configs.created_at IS '创建时间';
COMMENT ON COLUMN user_ai_model_configs.updated_at IS '更新时间';

CREATE INDEX idx_user_ai_model_configs_user_type_order
    ON user_ai_model_configs(user_id, model_type, sort_order, id);
CREATE UNIQUE INDEX uk_user_ai_model_configs_default
    ON user_ai_model_configs(user_id, model_type) WHERE is_default = TRUE;

-- 将旧总配置中的可用模型、默认模型和能力拆分到独立表；无法匹配渠道的模型不迁移。
WITH channel_models AS (
    SELECT c.user_id, c.channel_id, model.value AS model_name
    FROM user_ai_channels c
    CROSS JOIN LATERAL jsonb_array_elements_text(c.models) model(value)
    WHERE c.status = 1
), legacy_models AS (
    SELECT uc.user_id, 'image' AS model_type, value AS stored_model
    FROM user_configs uc CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(uc.settings_data #> '{config,imageModels}', '[]'::jsonb))
    UNION ALL
    SELECT uc.user_id, 'video', value
    FROM user_configs uc CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(uc.settings_data #> '{config,videoModels}', '[]'::jsonb))
    UNION ALL
    SELECT uc.user_id, 'text', value
    FROM user_configs uc CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(uc.settings_data #> '{config,textModels}', '[]'::jsonb))
), resolved AS (
    SELECT DISTINCT lm.user_id, lm.model_type, cm.channel_id, cm.model_name,
           COALESCE(uc.settings_data #> '{config,modelCapabilities}', '[]'::jsonb) AS capability_config,
           uc.settings_data #>> ARRAY['config', lm.model_type || 'Model'] AS default_model
    FROM legacy_models lm
    JOIN user_configs uc ON uc.user_id = lm.user_id
    JOIN channel_models cm ON cm.user_id = lm.user_id
      AND (lm.stored_model = cm.channel_id || '::' || cm.model_name OR lm.stored_model = cm.model_name)
)
INSERT INTO user_ai_model_configs(user_id, model_config_id, channel_id, model_name, model_type, capabilities, is_default, sort_order)
SELECT r.user_id,
       md5(r.user_id::text || ':' || r.channel_id || ':' || r.model_name || ':' || r.model_type),
       r.channel_id,
       r.model_name,
       r.model_type,
       COALESCE((SELECT item -> 'capabilities' FROM jsonb_array_elements(r.capability_config) item
                 WHERE item ->> 'model' IN (r.model_name, r.channel_id || '::' || r.model_name) LIMIT 1), '[]'::jsonb),
       r.default_model IN (r.model_name, r.channel_id || '::' || r.model_name),
       0
FROM resolved r
ON CONFLICT (user_id, channel_id, model_name, model_type) DO NOTHING;
