CREATE TABLE platform_ai_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(500) NOT NULL DEFAULT '',
    api_key_encrypted TEXT NOT NULL DEFAULT '',
    api_format VARCHAR(30) NOT NULL DEFAULT 'openai',
    models JSONB NOT NULL DEFAULT '[]'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_ai_channels IS '全站共享AI渠道配置表';
COMMENT ON COLUMN platform_ai_channels.id IS '主键ID';
COMMENT ON COLUMN platform_ai_channels.channel_id IS '渠道业务ID';
COMMENT ON COLUMN platform_ai_channels.name IS '渠道名称';
COMMENT ON COLUMN platform_ai_channels.base_url IS '渠道基础URL';
COMMENT ON COLUMN platform_ai_channels.api_key_encrypted IS '加密后的API Key';
COMMENT ON COLUMN platform_ai_channels.api_format IS '渠道调用格式';
COMMENT ON COLUMN platform_ai_channels.models IS '渠道完整模型名称列表';
COMMENT ON COLUMN platform_ai_channels.sort_order IS '排序值';
COMMENT ON COLUMN platform_ai_channels.status IS '状态：1正常，0删除';
COMMENT ON COLUMN platform_ai_channels.created_at IS '创建时间';
COMMENT ON COLUMN platform_ai_channels.updated_at IS '更新时间';

CREATE INDEX idx_platform_ai_channels_status_order
    ON platform_ai_channels(status, sort_order, id);

CREATE TABLE platform_ai_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_config_id VARCHAR(64) NOT NULL UNIQUE,
    channel_id VARCHAR(64) NOT NULL,
    model_name VARCHAR(200) NOT NULL,
    model_type VARCHAR(20) NOT NULL,
    capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_ai_model_configs_model UNIQUE (channel_id, model_name, model_type),
    CONSTRAINT ck_platform_ai_model_configs_type CHECK (model_type IN ('image', 'video', 'text')),
    CONSTRAINT fk_platform_ai_model_configs_channel FOREIGN KEY (channel_id) REFERENCES platform_ai_channels(channel_id)
);

COMMENT ON TABLE platform_ai_model_configs IS '全站可用AI模型配置表';
COMMENT ON COLUMN platform_ai_model_configs.id IS '主键ID';
COMMENT ON COLUMN platform_ai_model_configs.model_config_id IS '模型配置业务ID';
COMMENT ON COLUMN platform_ai_model_configs.channel_id IS '所属渠道业务ID';
COMMENT ON COLUMN platform_ai_model_configs.model_name IS '模型名称';
COMMENT ON COLUMN platform_ai_model_configs.model_type IS '模型类型：image、video、text';
COMMENT ON COLUMN platform_ai_model_configs.capabilities IS '模型能力列表JSON';
COMMENT ON COLUMN platform_ai_model_configs.is_default IS '是否为该类型默认模型';
COMMENT ON COLUMN platform_ai_model_configs.sort_order IS '排序值';
COMMENT ON COLUMN platform_ai_model_configs.created_at IS '创建时间';
COMMENT ON COLUMN platform_ai_model_configs.updated_at IS '更新时间';

CREATE INDEX idx_platform_ai_model_configs_type_order
    ON platform_ai_model_configs(model_type, sort_order, id);
CREATE UNIQUE INDEX uk_platform_ai_model_configs_default
    ON platform_ai_model_configs(model_type) WHERE is_default = TRUE;

CREATE TABLE platform_object_storage_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    provider VARCHAR(30) NOT NULL DEFAULT 'tencentCos',
    secret_id_encrypted TEXT NOT NULL DEFAULT '',
    secret_key_encrypted TEXT NOT NULL DEFAULT '',
    bucket VARCHAR(120) NOT NULL DEFAULT '',
    region VARCHAR(80) NOT NULL DEFAULT '',
    directory VARCHAR(200) NOT NULL DEFAULT '',
    public_base_url VARCHAR(500) NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    last_tested_at VARCHAR(64) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_object_storage_configs IS '全站共享对象存储配置表';
COMMENT ON COLUMN platform_object_storage_configs.id IS '主键ID';
COMMENT ON COLUMN platform_object_storage_configs.storage_id IS '对象存储业务ID';
COMMENT ON COLUMN platform_object_storage_configs.name IS '对象存储名称';
COMMENT ON COLUMN platform_object_storage_configs.provider IS '对象存储供应商';
COMMENT ON COLUMN platform_object_storage_configs.secret_id_encrypted IS '加密后的腾讯云SecretId';
COMMENT ON COLUMN platform_object_storage_configs.secret_key_encrypted IS '加密后的腾讯云SecretKey';
COMMENT ON COLUMN platform_object_storage_configs.bucket IS '腾讯云存储桶名称';
COMMENT ON COLUMN platform_object_storage_configs.region IS '腾讯云地域';
COMMENT ON COLUMN platform_object_storage_configs.directory IS '存储目录';
COMMENT ON COLUMN platform_object_storage_configs.public_base_url IS '公开访问基础URL';
COMMENT ON COLUMN platform_object_storage_configs.is_default IS '是否为默认对象存储';
COMMENT ON COLUMN platform_object_storage_configs.last_tested_at IS '最后测试时间';
COMMENT ON COLUMN platform_object_storage_configs.status IS '状态：1正常，0删除';
COMMENT ON COLUMN platform_object_storage_configs.created_at IS '创建时间';
COMMENT ON COLUMN platform_object_storage_configs.updated_at IS '更新时间';

CREATE INDEX idx_platform_object_storage_configs_status_order
    ON platform_object_storage_configs(status, is_default DESC, updated_at DESC, id ASC);
CREATE UNIQUE INDEX uk_platform_object_storage_configs_default
    ON platform_object_storage_configs(is_default) WHERE is_default = TRUE;

-- 线上已有配置仅从最早创建的管理员迁入，避免将多个管理员的付费渠道和密钥无提示合并。
WITH source_admin AS (
    SELECT id FROM users WHERE role = 'admin' ORDER BY created_at ASC, id ASC LIMIT 1
)
INSERT INTO platform_ai_channels(channel_id, name, base_url, api_key_encrypted, api_format, models, sort_order, status, created_at, updated_at)
SELECT channel_id, name, base_url, api_key_encrypted, api_format, models, sort_order, status, created_at, updated_at
FROM user_ai_channels
WHERE user_id = (SELECT id FROM source_admin) AND status = 1;

WITH source_admin AS (
    SELECT id FROM users WHERE role = 'admin' ORDER BY created_at ASC, id ASC LIMIT 1
)
INSERT INTO platform_ai_model_configs(model_config_id, channel_id, model_name, model_type, capabilities, is_default, sort_order, created_at, updated_at)
SELECT model_config_id, channel_id, model_name, model_type, capabilities, is_default, sort_order, created_at, updated_at
FROM user_ai_model_configs
WHERE user_id = (SELECT id FROM source_admin)
  AND channel_id IN (SELECT channel_id FROM platform_ai_channels);

WITH source_admin AS (
    SELECT id FROM users WHERE role = 'admin' ORDER BY created_at ASC, id ASC LIMIT 1
)
INSERT INTO platform_object_storage_configs(storage_id, name, provider, secret_id_encrypted, secret_key_encrypted, bucket, region, directory, public_base_url, is_default, last_tested_at, status, created_at, updated_at)
SELECT storage_id, name, provider, secret_id_encrypted, secret_key_encrypted, bucket, region, directory, public_base_url, is_default, last_tested_at, status, created_at, updated_at
FROM user_object_storage_configs
WHERE user_id = (SELECT id FROM source_admin) AND status = 1;
