ALTER TABLE platform_ai_model_configs
    ADD COLUMN credit_cost INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_platform_ai_model_configs_credit_cost CHECK (credit_cost >= 0);

COMMENT ON COLUMN platform_ai_model_configs.credit_cost IS '单次生成消耗积分';

CREATE TABLE platform_credit_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1,
    initial_credits INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_platform_credit_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_platform_credit_settings_initial_credits CHECK (initial_credits >= 0)
);

COMMENT ON TABLE platform_credit_settings IS '全站积分设置表';
COMMENT ON COLUMN platform_credit_settings.id IS '固定单行标识';
COMMENT ON COLUMN platform_credit_settings.initial_credits IS '新用户初始积分';
COMMENT ON COLUMN platform_credit_settings.created_at IS '创建时间';
COMMENT ON COLUMN platform_credit_settings.updated_at IS '更新时间';

INSERT INTO platform_credit_settings(id, initial_credits)
VALUES (1, 100);

CREATE TABLE user_credit_accounts (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    credit_balance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_credit_accounts_balance CHECK (credit_balance >= 0)
);

COMMENT ON TABLE user_credit_accounts IS '用户积分账户表';
COMMENT ON COLUMN user_credit_accounts.user_id IS '用户ID';
COMMENT ON COLUMN user_credit_accounts.credit_balance IS '当前可用积分';
COMMENT ON COLUMN user_credit_accounts.created_at IS '创建时间';
COMMENT ON COLUMN user_credit_accounts.updated_at IS '更新时间';

CREATE TABLE user_credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    transaction_type VARCHAR(30) NOT NULL,
    task_id VARCHAR(64) REFERENCES ai_generation_tasks(id),
    operator_user_id BIGINT REFERENCES users(id),
    change_amount INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    reason VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_credit_transactions_type CHECK (transaction_type IN ('initial_grant', 'task_charge', 'task_refund', 'admin_adjustment')),
    CONSTRAINT ck_user_credit_transactions_amount CHECK (change_amount <> 0),
    CONSTRAINT uk_user_credit_transactions_task_type UNIQUE (task_id, transaction_type)
);

COMMENT ON TABLE user_credit_transactions IS '用户积分流水表';
COMMENT ON COLUMN user_credit_transactions.id IS '流水ID';
COMMENT ON COLUMN user_credit_transactions.user_id IS '用户ID';
COMMENT ON COLUMN user_credit_transactions.transaction_type IS '流水类型：initial_grant、task_charge、task_refund、admin_adjustment';
COMMENT ON COLUMN user_credit_transactions.task_id IS '关联AI任务ID';
COMMENT ON COLUMN user_credit_transactions.operator_user_id IS '管理员操作用户ID';
COMMENT ON COLUMN user_credit_transactions.change_amount IS '积分变动值，正数增加、负数扣减';
COMMENT ON COLUMN user_credit_transactions.balance_after IS '变动后的账户余额';
COMMENT ON COLUMN user_credit_transactions.reason IS '积分变动原因';
COMMENT ON COLUMN user_credit_transactions.created_at IS '创建时间';

CREATE INDEX idx_user_credit_transactions_user_created
    ON user_credit_transactions(user_id, created_at DESC, id DESC);

INSERT INTO user_credit_accounts(user_id, credit_balance)
SELECT id, 100
FROM users;

INSERT INTO user_credit_transactions(user_id, transaction_type, task_id, operator_user_id, change_amount, balance_after, reason)
SELECT id, 'initial_grant', NULL, NULL, 100, 100, '存量用户初始发放'
FROM users;
