CREATE TABLE homepage_showcases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    media_type VARCHAR(20) NOT NULL,
    media_url VARCHAR(2048) NOT NULL,
    thumbnail_url VARCHAR(2048) NOT NULL DEFAULT '',
    target_type VARCHAR(20) NOT NULL,
    target_path VARCHAR(500) NOT NULL DEFAULT '',
    prompt_content TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 1000,
    status INTEGER NOT NULL DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE homepage_showcases IS '首页精选展示内容表';
COMMENT ON COLUMN homepage_showcases.id IS '首页精选内容ID';
COMMENT ON COLUMN homepage_showcases.title IS '展示标题';
COMMENT ON COLUMN homepage_showcases.description IS '展示描述';
COMMENT ON COLUMN homepage_showcases.media_type IS '媒体类型：image图片，video视频';
COMMENT ON COLUMN homepage_showcases.media_url IS '媒体地址';
COMMENT ON COLUMN homepage_showcases.thumbnail_url IS '视频缩略图地址';
COMMENT ON COLUMN homepage_showcases.target_type IS '目标类型：image图片，video视频，canvas画布，asset资产';
COMMENT ON COLUMN homepage_showcases.target_path IS '目标站内路径';
COMMENT ON COLUMN homepage_showcases.prompt_content IS '关联提示词';
COMMENT ON COLUMN homepage_showcases.sort_order IS '排序值，越小越靠前';
COMMENT ON COLUMN homepage_showcases.status IS '状态：1启用，0停用';
COMMENT ON COLUMN homepage_showcases.created_by IS '创建人用户ID';
COMMENT ON COLUMN homepage_showcases.created_at IS '创建时间';
COMMENT ON COLUMN homepage_showcases.updated_at IS '更新时间';
COMMENT ON COLUMN homepage_showcases.deleted_at IS '软删除时间';

CREATE INDEX idx_homepage_showcases_public ON homepage_showcases(status, deleted_at, sort_order, updated_at DESC, id DESC);
CREATE INDEX idx_homepage_showcases_admin ON homepage_showcases(deleted_at, updated_at DESC, id DESC);
