CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(100),
    nickname VARCHAR(50),
    avatar VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    status INTEGER NOT NULL DEFAULT 1,
    last_login_at TIMESTAMPTZ,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.id IS '用户ID';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.password IS '密码哈希';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.nickname IS '昵称';
COMMENT ON COLUMN users.avatar IS '头像URL';
COMMENT ON COLUMN users.role IS '角色：user普通用户，admin管理员';
COMMENT ON COLUMN users.status IS '状态：1正常，0禁用';
COMMENT ON COLUMN users.last_login_at IS '最后登录时间';
COMMENT ON COLUMN users.registered_at IS '注册时间';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.updated_at IS '更新时间';

CREATE TABLE user_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    config_data TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_configs_user_id UNIQUE (user_id)
);

COMMENT ON TABLE user_configs IS '用户配置表';
COMMENT ON COLUMN user_configs.id IS '配置ID';
COMMENT ON COLUMN user_configs.user_id IS '用户ID';
COMMENT ON COLUMN user_configs.config_data IS '加密后的配置JSON，包含AI、WebDAV、COS、主题和偏好';
COMMENT ON COLUMN user_configs.created_at IS '创建时间';
COMMENT ON COLUMN user_configs.updated_at IS '更新时间';

CREATE TABLE canvas_projects (
    id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    project_data JSONB NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE canvas_projects IS '画布项目表';
COMMENT ON COLUMN canvas_projects.id IS '画布项目ID';
COMMENT ON COLUMN canvas_projects.user_id IS '用户ID';
COMMENT ON COLUMN canvas_projects.title IS '画布标题';
COMMENT ON COLUMN canvas_projects.project_data IS '画布项目完整JSON快照';
COMMENT ON COLUMN canvas_projects.status IS '状态：1正常，0删除';
COMMENT ON COLUMN canvas_projects.created_at IS '创建时间';
COMMENT ON COLUMN canvas_projects.updated_at IS '更新时间';
CREATE INDEX idx_canvas_projects_user_status_updated ON canvas_projects(user_id, status, updated_at);

CREATE TABLE assets (
    id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    kind VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    asset_data JSONB NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE assets IS '素材表';
COMMENT ON COLUMN assets.id IS '素材ID';
COMMENT ON COLUMN assets.user_id IS '用户ID';
COMMENT ON COLUMN assets.kind IS '素材类型：text/image/video';
COMMENT ON COLUMN assets.title IS '素材标题';
COMMENT ON COLUMN assets.asset_data IS '素材完整JSON快照';
COMMENT ON COLUMN assets.status IS '状态：1正常，0删除';
COMMENT ON COLUMN assets.created_at IS '创建时间';
COMMENT ON COLUMN assets.updated_at IS '更新时间';
CREATE INDEX idx_assets_user_kind_updated ON assets(user_id, kind, updated_at);
CREATE INDEX idx_assets_user_status_updated ON assets(user_id, status, updated_at);

CREATE TABLE generation_logs (
    id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    log_type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    log_data JSONB NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE generation_logs IS '生成记录表';
COMMENT ON COLUMN generation_logs.id IS '生成记录ID';
COMMENT ON COLUMN generation_logs.user_id IS '用户ID';
COMMENT ON COLUMN generation_logs.log_type IS '记录类型：image/video';
COMMENT ON COLUMN generation_logs.title IS '记录标题';
COMMENT ON COLUMN generation_logs.log_data IS '生成记录完整JSON快照';
COMMENT ON COLUMN generation_logs.status IS '状态：1正常，0删除';
COMMENT ON COLUMN generation_logs.created_at IS '创建时间';
COMMENT ON COLUMN generation_logs.updated_at IS '更新时间';
CREATE INDEX idx_generation_logs_user_type_created ON generation_logs(user_id, log_type, created_at);
CREATE INDEX idx_generation_logs_user_status_created ON generation_logs(user_id, status, created_at);

CREATE TABLE media_files (
    storage_key VARCHAR(128) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    kind VARCHAR(30) NOT NULL,
    source_url VARCHAR(2048),
    cos_url VARCHAR(2048),
    cos_key VARCHAR(512),
    bucket VARCHAR(128),
    region VARCHAR(64),
    mime_type VARCHAR(100) NOT NULL,
    bytes BIGINT NOT NULL DEFAULT 0,
    width INTEGER,
    height INTEGER,
    duration_ms INTEGER,
    metadata JSONB,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE media_files IS '媒体文件元数据表';
COMMENT ON COLUMN media_files.storage_key IS '媒体存储键';
COMMENT ON COLUMN media_files.user_id IS '用户ID';
COMMENT ON COLUMN media_files.kind IS '媒体类型：image/video/audio/file等';
COMMENT ON COLUMN media_files.source_url IS '第三方远程原始URL';
COMMENT ON COLUMN media_files.cos_url IS '腾讯云COS公开URL';
COMMENT ON COLUMN media_files.cos_key IS '腾讯云COS对象Key';
COMMENT ON COLUMN media_files.bucket IS 'COS Bucket';
COMMENT ON COLUMN media_files.region IS 'COS Region';
COMMENT ON COLUMN media_files.mime_type IS 'MIME类型';
COMMENT ON COLUMN media_files.bytes IS '文件大小（字节）';
COMMENT ON COLUMN media_files.width IS '宽度（图片/视频）';
COMMENT ON COLUMN media_files.height IS '高度（图片/视频）';
COMMENT ON COLUMN media_files.duration_ms IS '时长（毫秒）';
COMMENT ON COLUMN media_files.metadata IS '媒体扩展元数据';
COMMENT ON COLUMN media_files.status IS '状态：1正常，0删除';
COMMENT ON COLUMN media_files.created_at IS '创建时间';
COMMENT ON COLUMN media_files.updated_at IS '更新时间';
CREATE INDEX idx_media_files_user_kind_updated ON media_files(user_id, kind, updated_at);
CREATE INDEX idx_media_files_user_status_updated ON media_files(user_id, status, updated_at);

CREATE TABLE api_request_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    request_id VARCHAR(64) NOT NULL,
    path VARCHAR(255) NOT NULL,
    method VARCHAR(10) NOT NULL,
    client_ip VARCHAR(50) NOT NULL,
    user_agent VARCHAR(500),
    params TEXT,
    response_code INTEGER,
    error_message VARCHAR(500),
    cost_ms INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_api_request_logs_request_id UNIQUE (request_id)
);

COMMENT ON TABLE api_request_logs IS 'API请求日志表';
COMMENT ON COLUMN api_request_logs.id IS '日志ID';
COMMENT ON COLUMN api_request_logs.user_id IS '用户ID，默认单用户固定为1';
COMMENT ON COLUMN api_request_logs.request_id IS '请求ID';
COMMENT ON COLUMN api_request_logs.path IS '请求路径';
COMMENT ON COLUMN api_request_logs.method IS '请求方法';
COMMENT ON COLUMN api_request_logs.client_ip IS '客户端IP';
COMMENT ON COLUMN api_request_logs.user_agent IS 'User-Agent';
COMMENT ON COLUMN api_request_logs.params IS '请求参数';
COMMENT ON COLUMN api_request_logs.response_code IS '响应码';
COMMENT ON COLUMN api_request_logs.error_message IS '错误信息';
COMMENT ON COLUMN api_request_logs.cost_ms IS '耗时（毫秒）';
COMMENT ON COLUMN api_request_logs.created_at IS '创建时间';
CREATE INDEX idx_api_request_logs_created_at ON api_request_logs(created_at);
