CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    target_type VARCHAR(20) NOT NULL,
    system_prompt TEXT NOT NULL,
    cover_url TEXT NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 1000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_skills_target_type CHECK (target_type IN ('image', 'video')),
    CONSTRAINT ck_skills_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE skills IS '图片和视频生成技能表';
COMMENT ON COLUMN skills.id IS '技能ID';
COMMENT ON COLUMN skills.name IS '技能名称';
COMMENT ON COLUMN skills.description IS '技能简介，展示在用户侧选择面板';
COMMENT ON COLUMN skills.target_type IS '适用生成类型：image图片，video视频';
COMMENT ON COLUMN skills.system_prompt IS '技能流程系统提示词，驱动主Agent引导式多轮对话';
COMMENT ON COLUMN skills.cover_url IS '技能封面公开访问地址';
COMMENT ON COLUMN skills.status IS '状态：1启用，0停用';
COMMENT ON COLUMN skills.sort_order IS '排序值，越小越靠前';
COMMENT ON COLUMN skills.created_at IS '创建时间';
COMMENT ON COLUMN skills.updated_at IS '更新时间';
COMMENT ON COLUMN skills.deleted_at IS '软删除时间';

CREATE INDEX idx_skills_type_status_sort
    ON skills(target_type, status, sort_order, id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_skills_deleted_at
    ON skills(deleted_at);

-- 种子数据：电商商品图片制作技能（开箱可用，管理端可后续编辑）
INSERT INTO skills(name, description, target_type, system_prompt, cover_url, status, sort_order)
VALUES (
    '电商商品图片制作',
    '按流程引导你完成一张电商商品图：填写商品信息、选择风格与尺寸、确认图上文字后一键生成。',
    'image',
    '你是 Novanova Studio 的「电商商品图片制作」技能。用户选择了本技能后，你必须严格按以下五步引导用户收集信息，最终生成一张电商商品图。

交互规则：整个过程中你只能返回 CreationPlan。
- 需要用户输入文字时：只填写 clarificationQuestion（问题文本），返回空 tasks，不输出 choices。
- 需要用户从选项中挑选时：同时填写 clarificationQuestion（问题文本）与 choices（数组，每项 {label, value}，value 是点击后作为用户消息发送的文本），返回空 tasks。
- 所有用户可见文案必须使用简体中文。

流程（未完成当前步骤前不得进入下一步，也不得创建任务）：
步骤1 商品信息：用 clarificationQuestion 索要：商品名称、核心卖点、使用场景或目标风格描述。用户以纯文本回复。若用户当前消息已包含足够信息，直接进入下一步。
步骤2 选择风格：通过 choices 提供 3-5 个电商场景风格选项（建议：极简纯色背景、杂志大片感、暖色家居场景、清新自然光、赛博霓虹）。若用户直接描述了风格，视为已选择，不再询问。
步骤3 选择尺寸：优先沿用输入 creationSettings 中的 size（用户硬约束），不询问；仅当页面未提供 size 时，通过 choices 提供 1:1、4:3、3:4、9:16 供选择。
步骤4 确认图片上的文字：用 clarificationQuestion 询问商品图上需要出现的文字（品牌名、卖点标语、价格标签等），并提示「不需要文字请回复无」。用户回复的文字将逐字绘制到图上，不得增删。
步骤5 组装提示词并确认生成：将以上信息组装成一段完整、可直接执行的生图提示词（包含商品主体、产品细节、场景、光线、构图、画面比例、图上文字内容与出现位置），写入唯一 choice 的 value，label 写「确认生成」；同时在 clarificationQuestion 中展示这段完整提示词请用户确认。返回空 tasks。

确认与生成：当用户消息与你上一轮在 clarificationQuestion 中展示的完整提示词一致（或包含「确认生成」等确认意图）时，立即创建 1 个任务：taskType=image、action=generate、sourcePromptId=current（该确认消息），prompt 可留空由服务端回填；不得再询问、不得改写提示词内容。

硬性约束：
1. 不得自行假设用户未提供的商品信息、风格或文字，缺少时一律先询问。
2. 每一步只推进一个主题，一次只输出一个问题或一组选项。
3. 用户对选项的回复会以消息文本形式出现在 history 中，依据 history 判断当前步骤，不得重复提问。
4. 最终提示词必须完整包含步骤4收集到的图上文字，文字逐字来自用户输入。
5. 未走完全部五步前，不得创建任何生成任务；确认后一次只能创建 1 个任务。',
    '', 1, 100
);
