-- 每日签到：平台签到积分配置、用户签到记录与签到积分流水类型

ALTER TABLE platform_credit_settings
    ADD COLUMN check_in_credits INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN check_in_streak_3_credits INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN check_in_streak_7_credits INTEGER NOT NULL DEFAULT 30,
    ADD COLUMN check_in_streak_14_credits INTEGER NOT NULL DEFAULT 60,
    ADD COLUMN check_in_streak_30_credits INTEGER NOT NULL DEFAULT 200,
    ADD CONSTRAINT ck_platform_credit_settings_check_in CHECK (
        check_in_credits >= 0
            AND check_in_streak_3_credits >= 0
            AND check_in_streak_7_credits >= 0
            AND check_in_streak_14_credits >= 0
            AND check_in_streak_30_credits >= 0
    );

COMMENT ON COLUMN platform_credit_settings.check_in_credits IS '每日签到基础积分，0表示签到不发放积分';
COMMENT ON COLUMN platform_credit_settings.check_in_streak_3_credits IS '连续签到满3天的额外奖励积分，0表示不发放';
COMMENT ON COLUMN platform_credit_settings.check_in_streak_7_credits IS '连续签到满7天的额外奖励积分，0表示不发放';
COMMENT ON COLUMN platform_credit_settings.check_in_streak_14_credits IS '连续签到满14天的额外奖励积分，0表示不发放';
COMMENT ON COLUMN platform_credit_settings.check_in_streak_30_credits IS '连续签到满30天的额外奖励积分，0表示不发放';

CREATE TABLE user_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    check_in_date DATE NOT NULL,
    streak_days INTEGER NOT NULL,
    base_credits INTEGER NOT NULL DEFAULT 0,
    bonus_credits INTEGER NOT NULL DEFAULT 0,
    bonus_streak_days INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_check_ins_user_date UNIQUE (user_id, check_in_date),
    CONSTRAINT ck_user_check_ins_streak CHECK (streak_days >= 1),
    CONSTRAINT ck_user_check_ins_credits CHECK (base_credits >= 0 AND bonus_credits >= 0),
    CONSTRAINT ck_user_check_ins_bonus CHECK ((bonus_credits > 0) = (bonus_streak_days IS NOT NULL)),
    CONSTRAINT ck_user_check_ins_bonus_streak CHECK (bonus_streak_days IS NULL OR bonus_streak_days IN (3, 7, 14, 30))
);

COMMENT ON TABLE user_check_ins IS '用户每日签到记录表';
COMMENT ON COLUMN user_check_ins.id IS '签到记录ID';
COMMENT ON COLUMN user_check_ins.user_id IS '签到用户ID';
COMMENT ON COLUMN user_check_ins.check_in_date IS '签到日期（Asia/Shanghai），同一用户同一天唯一';
COMMENT ON COLUMN user_check_ins.streak_days IS '本次签到后的连续签到天数，断签后重新从1开始';
COMMENT ON COLUMN user_check_ins.base_credits IS '本次签到发放的每日基础积分';
COMMENT ON COLUMN user_check_ins.bonus_credits IS '本次签到发放的连续签到额外奖励积分';
COMMENT ON COLUMN user_check_ins.bonus_streak_days IS '本次签到触发的连续签到里程碑天数，未触发为NULL';
COMMENT ON COLUMN user_check_ins.created_at IS '创建时间';

ALTER TABLE user_credit_transactions
    DROP CONSTRAINT ck_user_credit_transactions_type;

ALTER TABLE user_credit_transactions
    ADD CONSTRAINT ck_user_credit_transactions_type
        CHECK (transaction_type IN ('initial_grant', 'task_charge', 'task_refund', 'admin_adjustment', 'card_redeem', 'invitation_reward', 'daily_check_in'));

COMMENT ON COLUMN user_credit_transactions.transaction_type IS '流水类型：initial_grant、task_charge、task_refund、admin_adjustment、card_redeem、invitation_reward、daily_check_in';
