CREATE TABLE email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    send_count INTEGER NOT NULL DEFAULT 1,
    status INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE email_verification_codes IS '邮箱验证码表';
COMMENT ON COLUMN email_verification_codes.id IS '验证码ID';
COMMENT ON COLUMN email_verification_codes.email IS '邮箱';
COMMENT ON COLUMN email_verification_codes.code_hash IS '验证码哈希';
COMMENT ON COLUMN email_verification_codes.purpose IS '用途：register注册';
COMMENT ON COLUMN email_verification_codes.send_count IS '发送次数';
COMMENT ON COLUMN email_verification_codes.status IS '状态：0未使用，1已使用';
COMMENT ON COLUMN email_verification_codes.expires_at IS '过期时间';
COMMENT ON COLUMN email_verification_codes.used_at IS '使用时间';
COMMENT ON COLUMN email_verification_codes.created_at IS '创建时间';
COMMENT ON COLUMN email_verification_codes.updated_at IS '更新时间';
CREATE INDEX idx_email_codes_email_purpose_status ON email_verification_codes(email, purpose, status);
CREATE INDEX idx_email_codes_expires_at ON email_verification_codes(expires_at);

CREATE TABLE user_identity_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(128) NOT NULL,
    provider_email VARCHAR(100),
    provider_nickname VARCHAR(100),
    provider_avatar VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_identity_bindings_provider_user UNIQUE (provider, provider_user_id)
);

COMMENT ON TABLE user_identity_bindings IS '第三方身份绑定表';
COMMENT ON COLUMN user_identity_bindings.id IS '绑定ID';
COMMENT ON COLUMN user_identity_bindings.user_id IS '本地用户ID';
COMMENT ON COLUMN user_identity_bindings.provider IS '第三方登录渠道';
COMMENT ON COLUMN user_identity_bindings.provider_user_id IS '第三方用户ID';
COMMENT ON COLUMN user_identity_bindings.provider_email IS '第三方返回邮箱';
COMMENT ON COLUMN user_identity_bindings.provider_nickname IS '第三方返回昵称';
COMMENT ON COLUMN user_identity_bindings.provider_avatar IS '第三方返回头像';
COMMENT ON COLUMN user_identity_bindings.created_at IS '创建时间';
COMMENT ON COLUMN user_identity_bindings.updated_at IS '更新时间';
CREATE INDEX idx_user_identity_bindings_user_id ON user_identity_bindings(user_id);
CREATE INDEX idx_user_identity_bindings_provider_email ON user_identity_bindings(provider, provider_email);
