-- 签到积分有效期：会过期的积分发放批次台账 + 积分过期流水类型

CREATE TABLE user_credit_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    source_type VARCHAR(30) NOT NULL,
    source_ref VARCHAR(64),
    granted_amount INTEGER NOT NULL,
    remaining_amount INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_credit_grants_amount
        CHECK (granted_amount > 0 AND remaining_amount >= 0 AND remaining_amount <= granted_amount)
);

COMMENT ON TABLE user_credit_grants IS '会过期的积分发放批次表，目前仅每日签到发放写入；剩余额度之和不得超过用户积分余额';
COMMENT ON COLUMN user_credit_grants.id IS '发放批次ID';
COMMENT ON COLUMN user_credit_grants.user_id IS '用户ID';
COMMENT ON COLUMN user_credit_grants.source_type IS '发放来源流水类型，目前为daily_check_in';
COMMENT ON COLUMN user_credit_grants.source_ref IS '来源业务ID，如签到记录ID，用于追溯';
COMMENT ON COLUMN user_credit_grants.granted_amount IS '本次发放积分总数';
COMMENT ON COLUMN user_credit_grants.remaining_amount IS '尚未使用且尚未过期的积分，扣费按到期时间升序优先消耗';
COMMENT ON COLUMN user_credit_grants.expires_at IS '过期时间，签到发放取签到时刻后24小时';
COMMENT ON COLUMN user_credit_grants.created_at IS '创建时间';
COMMENT ON COLUMN user_credit_grants.updated_at IS '更新时间';

CREATE INDEX idx_user_credit_grants_fifo ON user_credit_grants(user_id, expires_at, id) WHERE remaining_amount > 0;

CREATE INDEX idx_user_credit_grants_expiring ON user_credit_grants(expires_at) WHERE remaining_amount > 0;

ALTER TABLE user_credit_transactions
    DROP CONSTRAINT ck_user_credit_transactions_type;

ALTER TABLE user_credit_transactions
    ADD CONSTRAINT ck_user_credit_transactions_type
        CHECK (transaction_type IN ('initial_grant', 'task_charge', 'task_refund', 'admin_adjustment', 'card_redeem', 'invitation_reward', 'daily_check_in', 'credit_expired'));

COMMENT ON COLUMN user_credit_transactions.transaction_type IS '流水类型：initial_grant、task_charge、task_refund、admin_adjustment、card_redeem、invitation_reward、daily_check_in、credit_expired';
