ALTER TABLE user_configs
    ADD COLUMN IF NOT EXISTS settings_data JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN user_configs.settings_data IS '用户普通配置JSON，不包含API Key、对象存储密钥和WebDAV密码';

CREATE TABLE user_ai_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    channel_id VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(500) NOT NULL DEFAULT '',
    api_key_encrypted TEXT NOT NULL DEFAULT '',
    api_format VARCHAR(30) NOT NULL DEFAULT 'openai',
    models JSONB NOT NULL DEFAULT '[]'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_ai_channels_user_channel UNIQUE (user_id, channel_id)
);

COMMENT ON TABLE user_ai_channels IS '用户AI渠道配置表';
COMMENT ON COLUMN user_ai_channels.id IS '渠道记录ID';
COMMENT ON COLUMN user_ai_channels.user_id IS '用户ID';
COMMENT ON COLUMN user_ai_channels.channel_id IS '前端渠道ID';
COMMENT ON COLUMN user_ai_channels.name IS '渠道名称';
COMMENT ON COLUMN user_ai_channels.base_url IS '渠道基础URL';
COMMENT ON COLUMN user_ai_channels.api_key_encrypted IS '加密后的API Key';
COMMENT ON COLUMN user_ai_channels.api_format IS '接口调用格式：openai、gemini、agnes';
COMMENT ON COLUMN user_ai_channels.models IS '渠道模型列表JSON';
COMMENT ON COLUMN user_ai_channels.sort_order IS '排序值';
COMMENT ON COLUMN user_ai_channels.status IS '状态：1正常，0删除';
COMMENT ON COLUMN user_ai_channels.created_at IS '创建时间';
COMMENT ON COLUMN user_ai_channels.updated_at IS '更新时间';
CREATE INDEX idx_user_ai_channels_user_status_order ON user_ai_channels(user_id, status, sort_order);

CREATE TABLE user_object_storage_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    storage_id VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    provider VARCHAR(30) NOT NULL DEFAULT 'tencentCos',
    secret_id_encrypted TEXT NOT NULL DEFAULT '',
    secret_key_encrypted TEXT NOT NULL DEFAULT '',
    bucket VARCHAR(128) NOT NULL DEFAULT '',
    region VARCHAR(64) NOT NULL DEFAULT '',
    directory VARCHAR(255) NOT NULL DEFAULT '',
    public_base_url VARCHAR(500) NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    last_tested_at VARCHAR(40) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_object_storage_user_storage UNIQUE (user_id, storage_id)
);

COMMENT ON TABLE user_object_storage_configs IS '用户对象存储配置表';
COMMENT ON COLUMN user_object_storage_configs.id IS '对象存储记录ID';
COMMENT ON COLUMN user_object_storage_configs.user_id IS '用户ID';
COMMENT ON COLUMN user_object_storage_configs.storage_id IS '前端对象存储配置ID';
COMMENT ON COLUMN user_object_storage_configs.name IS '对象存储名称';
COMMENT ON COLUMN user_object_storage_configs.provider IS '对象存储供应商';
COMMENT ON COLUMN user_object_storage_configs.secret_id_encrypted IS '加密后的SecretId';
COMMENT ON COLUMN user_object_storage_configs.secret_key_encrypted IS '加密后的SecretKey';
COMMENT ON COLUMN user_object_storage_configs.bucket IS '存储桶';
COMMENT ON COLUMN user_object_storage_configs.region IS '地域';
COMMENT ON COLUMN user_object_storage_configs.directory IS '上传目录';
COMMENT ON COLUMN user_object_storage_configs.public_base_url IS '公开访问基础URL';
COMMENT ON COLUMN user_object_storage_configs.is_default IS '是否默认对象存储';
COMMENT ON COLUMN user_object_storage_configs.last_tested_at IS '最后测试时间';
COMMENT ON COLUMN user_object_storage_configs.status IS '状态：1正常，0删除';
COMMENT ON COLUMN user_object_storage_configs.created_at IS '创建时间';
COMMENT ON COLUMN user_object_storage_configs.updated_at IS '更新时间';
CREATE INDEX idx_user_object_storage_user_status_updated ON user_object_storage_configs(user_id, status, updated_at);
CREATE UNIQUE INDEX uk_user_object_storage_default ON user_object_storage_configs(user_id) WHERE is_default = TRUE AND status = 1;

CREATE TABLE user_webdav_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    password_encrypted TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_webdav_configs_user UNIQUE (user_id)
);

COMMENT ON TABLE user_webdav_configs IS '用户WebDAV敏感配置表';
COMMENT ON COLUMN user_webdav_configs.id IS 'WebDAV配置ID';
COMMENT ON COLUMN user_webdav_configs.user_id IS '用户ID';
COMMENT ON COLUMN user_webdav_configs.password_encrypted IS '加密后的WebDAV密码';
COMMENT ON COLUMN user_webdav_configs.created_at IS '创建时间';
COMMENT ON COLUMN user_webdav_configs.updated_at IS '更新时间';
