CREATE TABLE generation_styles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_type VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    style_prompt TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 1000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_generation_styles_type CHECK (generation_type IN ('image', 'video')),
    CONSTRAINT ck_generation_styles_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE generation_styles IS '图片和视频生成风格表';
COMMENT ON COLUMN generation_styles.id IS '风格ID';
COMMENT ON COLUMN generation_styles.generation_type IS '生成类型：image图片，video视频';
COMMENT ON COLUMN generation_styles.name IS '风格名称';
COMMENT ON COLUMN generation_styles.style_prompt IS '风格提示词';
COMMENT ON COLUMN generation_styles.status IS '状态：1启用，0停用';
COMMENT ON COLUMN generation_styles.sort_order IS '排序值，越小越靠前';
COMMENT ON COLUMN generation_styles.created_at IS '创建时间';
COMMENT ON COLUMN generation_styles.updated_at IS '更新时间';
COMMENT ON COLUMN generation_styles.deleted_at IS '软删除时间';

CREATE INDEX idx_generation_styles_type_status_sort
    ON generation_styles(generation_type, status, sort_order, id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_generation_styles_deleted_at
    ON generation_styles(deleted_at);
