CREATE TABLE system_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    priority VARCHAR(10) NOT NULL DEFAULT 'normal',
    status INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE system_notifications IS '系统公告表';
COMMENT ON COLUMN system_notifications.id IS '公告ID';
COMMENT ON COLUMN system_notifications.title IS '公告标题';
COMMENT ON COLUMN system_notifications.content IS '公告内容';
COMMENT ON COLUMN system_notifications.priority IS '优先级：normal/high';
COMMENT ON COLUMN system_notifications.status IS '状态：0草稿，1已发布';
COMMENT ON COLUMN system_notifications.published_at IS '发布时间';
COMMENT ON COLUMN system_notifications.created_by IS '创建人用户ID';

CREATE TABLE user_notification_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    notification_id BIGINT NOT NULL,
    read_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_notification_read UNIQUE (user_id, notification_id)
);

COMMENT ON TABLE user_notification_reads IS '用户公告已读记录表';
COMMENT ON COLUMN user_notification_reads.user_id IS '用户ID';
COMMENT ON COLUMN user_notification_reads.notification_id IS '公告ID';
COMMENT ON COLUMN user_notification_reads.read_at IS '阅读时间';
CREATE INDEX idx_notification_reads_user ON user_notification_reads(user_id);
