-- ============================================================
-- 卡密批次、卡密库存与积分兑换流水
-- ============================================================
CREATE TABLE credit_card_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credits_per_card INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_credit_card_batches_credits CHECK (credits_per_card > 0),
    CONSTRAINT ck_credit_card_batches_quantity CHECK (quantity > 0 AND quantity <= 1000)
);

COMMENT ON TABLE credit_card_batches IS '积分卡密生成批次表';
COMMENT ON COLUMN credit_card_batches.id IS '批次ID';
COMMENT ON COLUMN credit_card_batches.credits_per_card IS '每张卡密可兑换的积分';
COMMENT ON COLUMN credit_card_batches.quantity IS '本批次生成数量';
COMMENT ON COLUMN credit_card_batches.created_by IS '创建批次的管理员用户ID';
COMMENT ON COLUMN credit_card_batches.created_at IS '批次创建时间';

CREATE TABLE credit_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES credit_card_batches(id),
    code_hash VARCHAR(64) NOT NULL,
    code_encrypted TEXT NOT NULL,
    code_masked VARCHAR(32) NOT NULL,
    code_suffix VARCHAR(4) NOT NULL,
    credits INTEGER NOT NULL,
    redeemed_by_user_id BIGINT REFERENCES users(id),
    redeemed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_credit_cards_code_hash UNIQUE (code_hash),
    CONSTRAINT ck_credit_cards_credits CHECK (credits > 0),
    CONSTRAINT ck_credit_cards_code_suffix CHECK (code_suffix ~ '^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}$')
);

COMMENT ON TABLE credit_cards IS '积分卡密库存表';
COMMENT ON COLUMN credit_cards.id IS '卡密ID';
COMMENT ON COLUMN credit_cards.batch_id IS '所属生成批次ID';
COMMENT ON COLUMN credit_cards.code_hash IS '规范化卡密的SHA-256摘要';
COMMENT ON COLUMN credit_cards.code_encrypted IS 'AES-GCM加密后的卡密';
COMMENT ON COLUMN credit_cards.code_masked IS '脱敏展示卡密';
COMMENT ON COLUMN credit_cards.code_suffix IS '卡密末四位，用于记录查询';
COMMENT ON COLUMN credit_cards.credits IS '本卡密可兑换的积分';
COMMENT ON COLUMN credit_cards.redeemed_by_user_id IS '兑换用户ID，未兑换时为空';
COMMENT ON COLUMN credit_cards.redeemed_at IS '兑换时间，未兑换时为空';
COMMENT ON COLUMN credit_cards.created_at IS '卡密创建时间';

CREATE INDEX idx_credit_cards_batch_status
    ON credit_cards(batch_id, redeemed_at, id);

CREATE INDEX idx_credit_cards_redeemed_user_time
    ON credit_cards(redeemed_by_user_id, redeemed_at DESC, id DESC)
    WHERE redeemed_by_user_id IS NOT NULL;

CREATE INDEX idx_credit_cards_suffix
    ON credit_cards(code_suffix);

ALTER TABLE user_credit_transactions
    ADD COLUMN credit_card_id BIGINT REFERENCES credit_cards(id);

ALTER TABLE user_credit_transactions
    DROP CONSTRAINT ck_user_credit_transactions_type;

ALTER TABLE user_credit_transactions
    ADD CONSTRAINT ck_user_credit_transactions_type
        CHECK (transaction_type IN ('initial_grant', 'task_charge', 'task_refund', 'admin_adjustment', 'card_redeem'));

ALTER TABLE user_credit_transactions
    ADD CONSTRAINT ck_user_credit_transactions_card_id
        CHECK (transaction_type <> 'card_redeem' OR credit_card_id IS NOT NULL);

COMMENT ON COLUMN user_credit_transactions.credit_card_id IS '关联兑换卡密ID，仅卡密兑换流水使用';
COMMENT ON COLUMN user_credit_transactions.transaction_type IS '流水类型：initial_grant、task_charge、task_refund、admin_adjustment、card_redeem';

CREATE INDEX idx_user_credit_transactions_card
    ON user_credit_transactions(credit_card_id)
    WHERE credit_card_id IS NOT NULL;

CREATE UNIQUE INDEX uk_user_credit_transactions_card_redeem
    ON user_credit_transactions(credit_card_id)
    WHERE transaction_type = 'card_redeem';
