CREATE TABLE prompt_library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    prompt_content TEXT NOT NULL,
    cover_url VARCHAR(2048) NOT NULL DEFAULT '',
    preview_content TEXT NOT NULL DEFAULT '',
    category VARCHAR(100) NOT NULL,
    tags_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_url VARCHAR(2048) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 1000,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE prompt_library IS '提示词库表';
COMMENT ON COLUMN prompt_library.id IS '提示词ID';
COMMENT ON COLUMN prompt_library.title IS '提示词标题';
COMMENT ON COLUMN prompt_library.prompt_content IS '提示词正文';
COMMENT ON COLUMN prompt_library.cover_url IS '封面图片URL';
COMMENT ON COLUMN prompt_library.preview_content IS '详情预览内容';
COMMENT ON COLUMN prompt_library.category IS '提示词分类';
COMMENT ON COLUMN prompt_library.tags_data IS '提示词标签JSON数组';
COMMENT ON COLUMN prompt_library.source_url IS '来源地址';
COMMENT ON COLUMN prompt_library.status IS '状态：1启用，0停用';
COMMENT ON COLUMN prompt_library.sort_order IS '排序值，越小越靠前';
COMMENT ON COLUMN prompt_library.created_by IS '创建人用户ID';
COMMENT ON COLUMN prompt_library.created_at IS '创建时间';
COMMENT ON COLUMN prompt_library.updated_at IS '更新时间';
COMMENT ON COLUMN prompt_library.deleted_at IS '软删除时间';

CREATE INDEX idx_prompt_library_user_list ON prompt_library(status, deleted_at, sort_order, updated_at DESC);
CREATE INDEX idx_prompt_library_category ON prompt_library(category);
CREATE INDEX idx_prompt_library_admin_list ON prompt_library(deleted_at, status, updated_at DESC);
